name: pymol
channels:
  - conda-forge
  - bioconda
  - schrodinger
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - ipykernel
  - ipywidgets
  - pymol
  - pymol-psico
  - rdkit
  - pip:
      - ipymol
      - pyqt5
