#!/usr/bin/env bash

# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Load seperate files
for file in ~/.config/bash/.bash_{aliases,functions,exports}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Case-insensitive globbing
shopt -s nocaseglob;

# Append to the Bash history file
shopt -s histappend;

# Autocorrect typos in path names when using 'cd'
shopt -s cdspell;

# Enable some Bash 4 features when possible:
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null;
done;

# Enable tab completion for 'g' as an alias for 'git'
if type _git &> /dev/null; then
    complete -o default -o nospace -F _git g;
fi;
